name: KamiKeys
version: 2.0.0
main: com.kamiplugins.kamikeys.Main
api-version: 1.20
author: Kamikash
description: Sistema de keys e vouchers para servidores Minecraft
commands:
  ativar:
    description: Ativa uma key
    usage: /ativar <codigo_da_key>
    permission: kamikeys.player
  keys:
    description: Abrir menu de key
    usage: /keys
    permission: kamikeys.player
  kamikeys:
    description: Comando administrativo do KamiKeys
    usage: /kamikeys <subcomando>
    permission: kamikeys.admin.*
permissions:
  kamikeys.admin.*:
    default: op
  kamikeys.admin.staff:
    default: op
  kamikeys.player:
    description: Permite ao jogador usar o comando /keys
    default: true
  kamikeys.voucher.player:
    default: op
